// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuoteQuiz.Api.Data;

#nullable disable

namespace QuoteQuiz.Api.Migrations
{
    [DbContext(typeof(QuoteQuizDbContext))]
    partial class QuoteQuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuoteQuiz.Api.Data.Models.QuizAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuizGameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("QuizGameId");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuizAnswers");
                });

            modelBuilder.Entity("QuoteQuiz.Api.Data.Models.QuizGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QuizGames");
                });

            modelBuilder.Entity("QuoteQuiz.Api.Data.Models.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7c8e4a1-2f3e-4c5d-9a8f-1b2c3d4e5f6a"),
                            Author = "Steve Jobs",
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "The only way to do great work is to love what you do."
                        },
                        new
                        {
                            Id = new Guid("c9d7f5b2-3a4f-5d6e-8b9c-2c3d4e5f6a7b"),
                            Author = "Steve Jobs",
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Innovation distinguishes between a leader and a follower."
                        },
                        new
                        {
                            Id = new Guid("d8e6a4c3-4b5a-6e7f-7c8a-3d4e5f6a7b8c"),
                            Author = "John Lennon",
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Life is what happens when you're busy making other plans."
                        },
                        new
                        {
                            Id = new Guid("e7f5b3d4-5c6a-7f8a-6d9b-4e5f6a7b8c9d"),
                            Author = "Eleanor Roosevelt",
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "The future belongs to those who believe in the beauty of their dreams."
                        },
                        new
                        {
                            Id = new Guid("f6a4c2e5-6d7a-8a9b-5e0c-5f6a7b8c9d0e"),
                            Author = "Aristotle",
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "It is during our darkest moments that we must focus to see the light."
                        },
                        new
                        {
                            Id = new Guid("a5b3d1e6-7e8a-9b0c-4f1a-6a7b8c9d0e1f"),
                            Author = "Walt Disney",
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "The way to get started is to quit talking and begin doing."
                        },
                        new
                        {
                            Id = new Guid("b4c2e0f7-8f9a-0c1b-3a2b-7b8c9d0e1f2a"),
                            Author = "Will Rogers",
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Don't let yesterday take up too much of today."
                        },
                        new
                        {
                            Id = new Guid("c3d1f9a8-9a0b-1d2c-2b3c-8c9d0e1f2a3b"),
                            Author = "Unknown",
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "You learn more from failure than from success."
                        },
                        new
                        {
                            Id = new Guid("d2e0a8b9-0b1c-2e3a-1c4b-9d0e1f2a3b4c"),
                            Author = "Vince Lombardi",
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "It's not whether you get knocked down, it's whether you get up."
                        },
                        new
                        {
                            Id = new Guid("e1f9b7ca-1c2a-3f4b-0d5a-0e1f2a3b4c5d"),
                            Author = "Tony Robbins",
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "The only impossible journey is the one you never begin."
                        });
                });

            modelBuilder.Entity("QuoteQuiz.Api.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3ee8240-662c-4c49-b9fd-da879be07766"),
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            IsActive = true,
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = new Guid("d3844151-b0ed-45cc-a8ee-b0c2de699fa8"),
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane@example.com",
                            IsActive = true,
                            Username = "jane_smith"
                        },
                        new
                        {
                            Id = new Guid("9beb8c94-3a41-408d-8572-696d3daa0289"),
                            CreatedAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            IsActive = true,
                            Username = "bob_wilson"
                        });
                });

            modelBuilder.Entity("QuoteQuiz.Api.Data.Models.QuizAnswer", b =>
                {
                    b.HasOne("QuoteQuiz.Api.Data.Models.QuizGame", "QuizGame")
                        .WithMany("QuizAnswers")
                        .HasForeignKey("QuizGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuoteQuiz.Api.Data.Models.Quote", "Quote")
                        .WithMany("QuizAnswers")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuizGame");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("QuoteQuiz.Api.Data.Models.QuizGame", b =>
                {
                    b.HasOne("QuoteQuiz.Api.Data.Models.User", "User")
                        .WithMany("QuizGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuoteQuiz.Api.Data.Models.QuizGame", b =>
                {
                    b.Navigation("QuizAnswers");
                });

            modelBuilder.Entity("QuoteQuiz.Api.Data.Models.Quote", b =>
                {
                    b.Navigation("QuizAnswers");
                });

            modelBuilder.Entity("QuoteQuiz.Api.Data.Models.User", b =>
                {
                    b.Navigation("QuizGames");
                });
#pragma warning restore 612, 618
        }
    }
}
